### ISSUE TITLE
Concrete items definition

### ISSUE THREAD

**Issue by bell07** [duane-r/cityscape#2]
Something is wrong with concrete items definition. I know this mod is abandoned but please check the reason if other mods maybe affected too.
`print(minetest.registered_items["cityscape:concrete3"].name)`
get the result `cityscape:concrete5`

I found the issue because the smart_inventory was crashing in recipe analysis (worked around now)

**Comment by duane-r** [comment]
I left out the intervening clone_node calls. This is the similar fix to Squaresville: https://github.com/duane-r/squaresville/commit/aa87e11429e2e43d0524993dc480d3108e833798
